QA/QA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('student/', include('students.urls')),
    path('teacher/', include('teachers.urls')),
]

QA/students/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
    path('dashboard', views.student_dashboard, name='student_dashboard'),
    path('student-profile', views.student_profile, name='student_profile'),
    path('student-logout', views.student_logout, name='student_logout'),
    path('student-question-page', views.student_question_page, name='student_question_page'),
    path('student-update-profile', views.student_update_profile, name='student_update_profile'),
    path('student-answer/<int:id>', views.student_answer, name='student_answer'),
    path('delete-question/<int:id>', views.delete_question, name='delete_question'),
    path('delete-question-confirm/<int:id>', views.delete_question_confirm, name='delete_question_confirm'),
]

QA/students/models.py
from django.db import models
from django.conf import settings

class QuestionManager(models.Manager):
    def get_specialised_questions(self,specialty):
        return super().get_queryset().filter(specialty=specialty)
    def specialised_questions_count(self,specialty):
        questions_count = super().get_queryset().filter(specialty=specialty).count()
        if questions_count == 1:
            return f'You have unanswer {questions_count} question'
        else:
            return f'You have unanswer {questions_count} questions'
class StudentQuestion(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, to_field='username', null=False)
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.EmailField()
    question = models.TextField(blank=False, null=False)
    specialty = models.CharField(max_length=100, blank=False)

    question_manager = QuestionManager()

    class Meta:
        db_table = 'StudentQuestion'
    def __str__(self):
        return self.name

QA/students/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import StudentQuestion
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from teachers.models import QuestionAnswer

@login_required(login_url='base:login')
def student_dashboard(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        email = request.POST.get('email')
        question = request.POST.get('question')
        specialty = request.POST.get('speciality')
        
        if user.name != name and user.email != email:
            messages.error(request, 'This is not your email or name')
            return redirect('student:student_dashboard')
        else:
            messages.success(request, 'Question sucessfully asked')
            student_question = StudentQuestion.question_manager.create(student=user,name=name, email=email, question=question, specialty=specialty)
            student_question.save()
            return redirect('student:student_question_page')
    return render(request, 'studentdashboard.html')

@login_required(login_url='base:login')
def student_profile(request):
    user = request.user
    return render(request, 'studentprofile.html',{'user':user})

@login_required(login_url='base:login')
def student_question_page(request):
    user = request.user
    questions = StudentQuestion.question_manager.filter(student=user)
    return render(request, "studentquestionpage.html", {'questions':questions})

@login_required(login_url='base:login')
def student_answer(request, id):
    question_answer = StudentQuestion.question_manager.get(id=id) 
    # question = QuestionAnswer.objects.get(id=id) 
    return render(request, 'studentanswer.html', {'question_answer':question_answer})

@login_required(login_url='base:login')
def student_update_profile(request):
    user = request.user
    if request.method == 'POST':
        if user.is_authenticated:
            name = request.POST.get("name")
            email = request.POST.get("email")
            uname = request.POST.get("uname")
            userr = request.POST.get("user")
            user.name = name
            user.email = email
            user.username = uname
            user.user = userr
            user.save()
            return redirect('teacher:teacher_profile' )
    return render(request, 'teachereditprofile.html')

@login_required(login_url='base:login')
def student_logout(request):
    logout(request)
    if 'student' in request.session:
        del request.session['student']
    return redirect('base:login') 

def delete_question(request, id):
    question = get_object_or_404(StudentQuestion, id=id)
    return render(request, 'question_delete.html', {'question': question})

def delete_question_confirm(request, id):
    question = get_object_or_404(StudentQuestion, id=id)
    question.delete()
    return redirect('student:student_question_page')

QA/students/templates/question_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1 class=" text-center">Are you sure you want to delete the question?</h1>
        <div class="container">
        </div>
        <div class="mt-5 gap-2">
            <a href="{%url 'student:student_question_page' %}"><button type="button" class="btn btn-secondary btn-sm p-3">Go back</button></a>
            <a href="{%url 'student:delete_question_confirm' question.id %}"><button type="button" class="btn btn-danger btn-sm p-3">Delete</button></a>
        </div>
    </div>    
</body>
</html>

QA/students/templates/studentanswer.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <link rel="stylesheet" href="{%static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        strong {
            font-size: 15px;
        }

        button {
            margin: 5px 5px 0px 0px;
        }

        table {
            font-size: large;
            margin-top: 5%;
            margin-left: 20px;
        }

        h2 {
            margin-left: 20px;
            margin-top: 5%;
        }

        a {
            text-decoration: none;
        }
    </style>
</head>

<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img"
            aria-label="Warning:">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        <strong>{{message}}</strong>
    </div>
    {%endfor%}
    {%endif%}


    <header class="header">

        <section class="flex">
            {%if user.is_authenticated%}
            <a href="{%url 'student:student_dashboard' %}" class="logo">Welcome {{user.username}}</a>
            {%endif%}

            <div class="icons">
                <div id="user-btn" class="fas fa-user"></div>
                <div id="toggle-btn" class="fas fa-sun"></div>
            </div>

            
            <div class="profile">
                <img src="{%static 'img/R.jpg'%}" class="image" alt="">
                <h3 class="name">{{user.name}}</h3>
                <p class="role">{{user.user|capfirst}}</p>
                <a href="{%url 'student:student_profile' %}" class="option-btn">view profile</a>
                <div class="flex-btn">
                    <a href="{%url 'student:student_logout' %}" class="option-btn">logout</a>
                </div>
            </div>

        </section>

    </header>

    <div class="side-bar">

        <div id="close-btn">
            <i class="fas fa-times"></i>
        </div>


    </div>

    </div>
    </div>

    </div>


    <h2 class="h2 text-center mt-5">Answer to your question</h2>
    <div class="container text-center mt-5 pt-5 fs-5">
        <p >{{question_answer.question}}</p>
        <!-- <h1>{{question.answer}}</h1> -->
    </div>
    <div class="container mt-5">
        <a href="{%url 'student:delete_question' question_answer.id%}"><button type="button" class="btn btn-danger">Delete</button></a>
        <a href="{%url 'student:student_question_page' %}"><button type="button" class="btn btn-success">Go back</button></a>
    </div>
    

    <script src="{%static 'js/base.js' %}"></script>
</body>

</html>



    
</body>
</html>

QA/students/templates/studentdashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <link rel="stylesheet" href="{%static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        strong {
            font-size: 15px;
        }

        button {
            margin: 5px 5px 0px 0px;
        }
        .small{
            font-size: 15px;
        }
        #category{
            color: white;
        }
    </style>
</head>

<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <strong>{{message}}</strong>
    </div>
    {%endfor%}
    {%endif%}
    {%if user.is_authenticated%}

    <header class="header">

        <section class="flex">


            <a href="{%url 'student:student_profile' %}" class="logo">Welcome {{user.username}}</a>


            <div class="icons">
                <div id="user-btn" class="fas fa-user"></div>
                <div id="toggle-btn" class="fas fa-sun"></div>
            </div>

            <div class="profile">
                <img src="{%static 'img/R.jpg'%}" class="image" alt="">
                <h3 class="name">{{user.name}}</h3>
                <p class="role">{{user.user|capfirst}}</p>
                <a href="{%url 'student:student_question_page'%}" class="option-btn">Questions</a>
                <a href="{%url 'student:student_profile' %}" class="option-btn">view profile</a>
                <div class="flex-btn">
                    <a href="{%url 'student:student_logout' %}" class="option-btn">logout</a>
                </div>
            </div>

        </section>

    </header>

    <div class="side-bar">

        <div id="close-btn">
            <i class="fas fa-times"></i>
        </div>
    </div>

    </div>

    <section class="contact">

        <div class="row">

            <div class="image">
                <img src="{%static 'img/contact-img.svg' %}" alt="">
            </div>

            <form method="post">
                {%csrf_token%}
                <h3>Question?</h3>
                <div class="container mt-5">
                    <label class="small" id="category">Category of question</label>
                    <select class="form-control small"name="speciality">
                       <option value=""></option>
                       <option value="Web Dev">Web Developer</option>
                       <option value="Linux">Linux Administration</option>
                    </select>
                 </div>
                <input type="name" placeholder="enter your name" name="name" required maxlength="255" class="box">
                <input type="email" placeholder="enter your email" name="email" required maxlength="255" class="box">
                <textarea name="question" class="box" placeholder="enter your question" required maxlength="1000"
                    cols="30" rows="10"></textarea>
                <input type="submit" value="Ask Question" class="inline-btn" name="submit">
            </form>

        </div>

        </div>

    </section>
    <script src="{%static 'js/base.js' %}"></script>
    {%endif%}
</body>

</html>

QA/students/templates/studentprofile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {%load static%}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
    />
    <link rel="stylesheet" href="{%static 'base.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <style>
      strong {
        font-size: 15px;
      }

      button {
        margin: 5px 5px 0px 0px;
      }

      .btn {
        padding-top: 3px;
      }

      table {
        font-size: large;
        margin-top: 5%;
        margin-left: 20px;
      }

      h2 {
        margin-left: 20px;
        margin-top: 5%;
      }
    </style>
  </head>

  <body>
    {%if messages%} {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"
        viewBox="0 0 16 16"
        role="img"
        aria-label="Warning:"
      >
        <path
          d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
        />
      </svg>
      <strong>{{message}}</strong>
    </div>
    {%endfor%} {%endif%}

    <header class="header">
      <section class="flex">
        

        <a href="{%url 'student:student_dashboard' %}" class="logo">Welcome {{user.username}}</a>

        <div class="icons">
          <div id="user-btn" class="fas fa-user"></div>
          <div id="toggle-btn" class="fas fa-sun"></div>
        </div>

        <div class="profile">
          <img src="{%static 'img/R.jpg'%}" class="image" alt="" />
          <h3 class="name">{{user.name}}</h3>
          <p class="role">{{user.user|capfirst}}</p>
          <div class="flex-btn">
            <a href="{%url 'student:student_logout' %}" class="option-btn"
              >logout</a
            >
          </div>
        </div>
      </section>
    </header>

    <div class="d-flex align-items-center justify-content-center mt-4">
      <img
        src="{%static 'img/R.jpg'%}"
        class="rounded-pill"
        width="100"
        height="100"
        alt="Profile picture"
      />
    </div>
    <div class="card-body text-center fs-5">
      <div class="user-info">
        <p><strong>Username: {{user.username|capfirst}}</strong></p>
        <p><strong>Email Address: {{user.email|capfirst}}</strong></p>
        <p><strong>Full Name: {{user.name|capfirst}}</strong></p>
        <p><strong>User: {{user.user_type|capfirst}}</strong></p>
      </div>
      <a href="{%url 'student:student_update_profile' %}" class="btn btn-primary btn-block">Edit Profile</a>
    </div>

    <script src="{%static 'js/base.js' %}"></script>
  </body>
</html>

QA/students/templates/studentquestionpage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <link rel="stylesheet" href="{%static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        strong {
            font-size: 15px;
        }

        button {
            margin: 5px 5px 0px 0px;
        }

        table {
            font-size: large;
            margin-top: 5%;
            margin-left: 20px;
        }

        h2 {
            margin-left: 20px;
            margin-top: 5%;
        }

        a {
            text-decoration: none;
        }
    </style>
</head>

<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img"
            aria-label="Warning:">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        <strong>{{message}}</strong>
    </div>
    {%endfor%}
    {%endif%}


    <header class="header">

        <section class="flex">
            {%if user.is_authenticated%}
            <a href="{%url 'student:student_dashboard' %}" class="logo">Welcome {{user.username}}</a>
            {%endif%}

            <div class="icons">
                <div id="user-btn" class="fas fa-user"></div>
                <div id="toggle-btn" class="fas fa-sun"></div>
            </div>

            
            <div class="profile">
                <img src="{%static 'img/R.jpg'%}" class="image" alt="">
                <h3 class="name">{{user.name}}</h3>
                <p class="role">{{user.user|capfirst}}</p>
                <a href="{%url 'student:student_profile' %}" class="option-btn">view profile</a>
                <div class="flex-btn">
                    <a href="{%url 'student:student_logout' %}" class="option-btn">logout</a>
                </div>
            </div>

        </section>

    </header>

    <div class="side-bar">

        <div id="close-btn">
            <i class="fas fa-times"></i>
        </div>


    </div>

    </div>
    </div>

    </div>

    <h2>Past questions</h2>
    <table class="table table-striped text-center">
        <thead>
            <tr>
                <th>Questions</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {%for question in questions%}
            <tr>
                <td>{{question.question}}</td>
                <td><a href="{%url 'student:student_answer' question.id %}"><button type="button"class="btn btn-success fs-4">Check</button></a></td>
            </tr>
            {%endfor%}

        </tbody>
    </table>


    </section>
    <script src="{%static 'js/base.js' %}"></script>
</body>

</html>

