QA/QA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('student/', include('students.urls')),
    path('teacher/', include('teachers.urls')),
]

QA/teachers/urls.py
from django.urls import path
from . import views

app_name = 'teacher'
urlpatterns = [
    path('dashboard', views.teacher_dashboard, name='teacher_dashboard'),
    path('logout', views.teacher_logout, name='teacher_logout'),
    path('teacher-profile', views.teacher_profile, name='teacher_profile'),
    path('teacher-update-profile', views.teacher_update_profile, name='teacher_update_profile'),
    path('teacher-question/<int:id>', views.teacher_question, name='teacher_question'),
]

QA/teachers/models.py
from django.db import models
from students.models import StudentQuestion


class QuestionAnswer(models.Model):
    question = models.ForeignKey(StudentQuestion, on_delete=models.PROTECT, null=True) #related_name=answer: It is use for one to one field
    answer = models.TextField()

    class Meta:
        db_table = 'QuestionAnswer'
    def __str__(self):
        return self.question

QA/teachers/views.py
from django.shortcuts import render, get_object_or_404
from students.models import StudentQuestion
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import QuestionAnswer

@login_required(login_url='base:login')
def teacher_dashboard(request):
    user = request.user
    if user.specialty is not None:
        question_count = StudentQuestion.question_manager.specialised_questions_count(specialty=user.specialty)
        questions = StudentQuestion.question_manager.get_specialised_questions(specialty=user.specialty)
    context = {'questions':questions, 'question_count':question_count}
    return render(request, 'teacherdashboard.html', context)

@login_required(login_url='base:login')
def teacher_profile(request):
    return render(request, 'teacherprofile.html')

@login_required(login_url='base:login')
def teacher_update_profile(request):
    user = request.user
    if request.method == 'POST':
        if user.is_authenticated:
            name = request.POST.get("name")
            email = request.POST.get("email")
            uname = request.POST.get("uname")
            user_type = request.POST.get("user_type")
            user.name = name
            user.email = email
            user.username = uname
            user.user_type = user_type
            user.save()
            return redirect('teacher:teacher_profile' )
    return render(request, 'teachereditprofile.html')

@login_required(login_url='base:login')
def teacher_logout(request):
    logout(request)
    if 'teacher' in request.session:
        del request.session['teacher']
    return redirect('base:login') 

@login_required(login_url='base:login')
def teacher_question(request, id):
    question = get_object_or_404(StudentQuestion, id=id)
    if request.method == 'POST':
        teacher_answer = request.POST.get('answer')
        answer = QuestionAnswer.objects.create(answer=teacher_answer)
        answer.save()
    return render(request, 'teacheranswer.html', {'question':question})

QA/teachers/templates/teacheranswer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h5>{{ question.question}}</h5>
    <form method="POST">
        {% csrf_token %}
        <textarea name="answer"></textarea>
        <input type="submit" value="Answer">
    </form>
</body>
</html>

QA/teachers/templates/teacherdashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load static%}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <link rel="stylesheet" href="{%static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        strong {
            font-size: 15px;
        }

        button {
            margin: 5px 5px 0px 0px;
        }

        table {
            font-size: large;
            margin-top: 5%;
            margin-left: 20px;
        }

        h2 {
            margin-left: 20px;
            margin-top: 5%;
        }
    </style>
</head>

<body>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img"
            aria-label="Warning:">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        <strong>{{message}}</strong>
    </div>
    {%endfor%}
    {%endif%}


    <header class="header">

        <section class="flex">
            {%if user.is_authenticated%}

            <a href="{%url 'teacher:teacher_profile' %}" class="logo">Welcome {{user.username}}</a>
            {%endif%}

            <div class="icons">
                <div id="user-btn" class="fas fa-user"></div>
                <div id="toggle-btn" class="fas fa-sun"></div>
            </div>

            <div class="profile">
                <img src="{%static 'img/R.jpg'%}" class="image" alt="">
                <h3 class="name">{{user.name}}</h3>
                <p class="role">{{user.user|capfirst}}</p>
                <a href="{%url 'teacher:teacher_profile' %}" class="option-btn">view profile</a>
                <div class="flex-btn">
                    <a href="{%url 'teacher:teacher_logout' %}" class="option-btn">logout</a>
                </div>
            </div>

        </section>

    </header>

    <div class="side-bar">

        <div id="close-btn">
            <i class="fas fa-times"></i>
        </div>


    </div>

    </div>
    </div>

    </div>
    <h2>{{question_count}}</h2>
    <table class="table table-striped ">
        <thead>
            <tr>
                <th>Student</th>
                <th>Question</th>
                <th>email</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {%for question in questions%}
            <tr>
                <td>{{question.student_id}}</td>
                <td><a href="{%url 'teacher:teacher_question' question.id %}">{{question.question}}</a></td>
                <td>{{question.email}}</td>
                <td></td>
            </tr>
            {%endfor%}

        </tbody>
    </table>


    </section>
    <script src="{%static 'js/base.js' %}"></script>
</body>

</html>

QA/teachers/templates/teachereditprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
   {% load static %}
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <link rel="stylesheet" href="{%static 'base.css'%}">
   
</head>
<body>
    {%if user.is_authenticated%}
   {%if messages%}
   {%for message in messages%}
   <div class="alert alert-warning alert-dismissabe fade show">
      <span>{{message}}</span>
      <button type="button" class="btn-colse" data-bs-dismiss="alert"></button>
   {%endfor%}
   {%endif%}

    <section class="form-container">
        <form method="post">
            {%csrf_token%}
            <h3>Update profile</h3>
            <p>Username <span>*</span></p>
            <input type="text" name="uname" value="{{user.username}}" placeholder="enter your username" required maxlength="50" class="box">
            <p>Full Name <span>*</span></p>
            <input type="text" name="name" value="{{user.name}}" placeholder="enter your name" required maxlength="50" class="box">
            <p>Teacher or student <span>*</span></p>
            <input type="radio" {% if user.user_type == 'teacher' %} checked {% endif %} name="user_type" value="teacher" class="box">
            <input type="radio" {% if user.user_type == 'student' %} checked {% endif %} name="user_type" value="student" class="box">
            

            <p>Email <span>*</span></p>
            <input type="email" name="email" value="{{user.email}}" placeholder="enter your email" required maxlength="50" class="box">
            <input type="submit" value="Update" name="submit" class="btn">
        </form>
    </section>
   <script src="js/script.js"></script>
   {%endif%}
</body>
</html>

QA/teachers/templates/teacherprofile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {%load static%}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
    />
    <link rel="stylesheet" href="{%static 'base.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <style>
      strong {
        font-size: 15px;
      }

      button {
        margin: 5px 5px 0px 0px;
      }

      .btn {
        padding-top: 3px;
      }

      table {
        font-size: large;
        margin-top: 5%;
        margin-left: 20px;
      }

      h2 {
        margin-left: 20px;
        margin-top: 5%;
      }
    </style>
  </head>

  <body>
    {%if user.is_authenticated%}
    {%if messages%} {%for message in messages%}
    <div class="alert alert-warning d-flex align-items-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"
        viewBox="0 0 16 16"
        role="img"
        aria-label="Warning:"
      >
        <path
          d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
        />
      </svg>
      <strong>{{message}}</strong>
    </div>
    {%endfor%} {%endif%}

    <header class="header">
      <section class="flex">
        

        <a href="{%url 'teacher:teacher_dashboard' %}" class="logo">Welcome {{user.username}}</a>

        <div class="icons">
          <div id="user-btn" class="fas fa-user"></div>
          <div id="toggle-btn" class="fas fa-sun"></div>
        </div>

        <div class="profile">
          <img src="{%static 'img/R.jpg'%}" class="image" alt="" />
          <h3 class="name">{{user.name}}</h3>
          <p class="role">{{user.user|capfirst}}</p>
          <div class="flex-btn">
            <a href="{%url 'teacher:teacher_logout' %}" class="option-btn"
              >logout</a
            >
          </div>
        </div>
      </section>
    </header>

    <div class="d-flex align-items-center justify-content-center mt-4">
      <img
        src="{%static 'img/R.jpg'%}"
        class="rounded-pill"
        width="100"
        height="100"
        alt="Profile picture"
      />
    </div>
    <div class="card-body text-center fs-5">
      <h5 class="card-title text-center">User Information</h5>
      <div class="user-info">
        <p><strong>Username: {{user.username}}</strong></p>
        <p><strong>Email Address: {{user.email}}</strong></p>
        <p><strong>Full Name: {{user.name}}</strong></p>
        <p><strong>User: {{user.user_type|capfirst}}</strong></p>
      </div>
      <a href="{%url 'teacher:teacher_update_profile' %}" class="btn btn-primary btn-block">Edit Profile</a>
    </div>

    <script src="{%static 'js/base.js' %}"></script>
    {%endif%}
  </body>
</html>